<?php

/**
 * @file
 * A dummy module for testing node setDisplayConfigurable.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function node_display_configurable_test_entity_base_field_info_alter(&$base_field_definitions, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    foreach (['created', 'uid', 'title'] as $field) {
      $base_field_definitions[$field]->setDisplayConfigurable('view', TRUE);
    }
  }
}
