<?php

/**
 * @file
 * A module for testing setDisplayConfigurable on node base fields.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function node_display_configurable_test_entity_base_field_info_alter(&$base_field_definitions, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    foreach (['created', 'uid', 'title'] as $field) {
      $base_field_definitions[$field]->setDisplayConfigurable('view', TRUE);
    }
  }
}

/**
 * Implements hook_entity_type_build().
 */
function node_display_configurable_test_entity_type_build(array &$entity_types) {
  // Must disable extra preprocessing for configurable display.
  $entity_types['node']->set('bypass_base_preprocess', TRUE);
}
